# travis-ci configuration
language: python
python:
  - "2.7"
install:
  - pip install -e . --use-mirrors
  - pip install coveralls --use-mirrors
script:
  - nosetests --with-coverage --cover-package=ipydb
  - flake8 --exit-zero ipydb
after_success:
  - coveralls
